/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package security;

import java.math.BigInteger;
import java.security.SecureRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author hema
 */
public class RSA extends javax.swing.JFrame {

    /**
     * Creates new form RSA
     */
    public RSA() {
        initComponents();
        this.setLocation(100, 3);
        this.setTitle("RSA");
        jLabel8.setVisible(false);
        lin.setVisible(false);
    }
    // varables we need
    //'a','b','c','d','e','f','g','h','i','j','k','l''m','n','o','p','q','r','s','t','u','v','w','x','y','z'
    //               0    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27    28  29   30    33   34   35   36   37  38
    char[] array = {' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};
    char[] array1 = {' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
    char[] array2 = {' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};
    char[] array3;
    BigInteger p;
    BigInteger q;
    BigInteger pp;
    BigInteger qq;
    BigInteger e;
    BigInteger ee;
    BigInteger d;
    BigInteger dd;
    BigInteger n;
    BigInteger nn;
    BigInteger z;
    BigInteger zz;
    BigInteger nd;
    BigInteger ndd;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p1 = new javax.swing.JLabel();
        tp1 = new javax.swing.JTextField();
        tq1 = new javax.swing.JTextField();
        q1 = new javax.swing.JLabel();
        tz1 = new javax.swing.JTextField();
        z1 = new javax.swing.JLabel();
        tn1 = new javax.swing.JTextField();
        n1 = new javax.swing.JLabel();
        td1 = new javax.swing.JTextField();
        d1 = new javax.swing.JLabel();
        te1 = new javax.swing.JTextField();
        e1 = new javax.swing.JLabel();
        pk1 = new javax.swing.JLabel();
        tpk1 = new javax.swing.JTextField();
        tprk1 = new javax.swing.JTextField();
        prk1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tprk2 = new javax.swing.JTextField();
        prk2 = new javax.swing.JLabel();
        pk2 = new javax.swing.JLabel();
        tpk2 = new javax.swing.JTextField();
        td2 = new javax.swing.JTextField();
        d2 = new javax.swing.JLabel();
        te2 = new javax.swing.JTextField();
        e2 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        tn2 = new javax.swing.JTextField();
        z2 = new javax.swing.JLabel();
        tz2 = new javax.swing.JTextField();
        tq2 = new javax.swing.JTextField();
        q2 = new javax.swing.JLabel();
        tp2 = new javax.swing.JTextField();
        p2 = new javax.swing.JLabel();
        FillB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        EnAtoB = new javax.swing.JButton();
        EnBtoA = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DeAtoB = new javax.swing.JButton();
        DeBtoA = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FillAuto = new javax.swing.JButton();
        FillA = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1.setText("p");

        q1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q1.setText("q");

        z1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        z1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        z1.setText("z");

        n1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n1.setText("n");

        d1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d1.setText("d");

        e1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e1.setText("e");

        pk1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pk1.setText("public key");

        tpk1.setColumns(15);
        tpk1.setMaximumSize(new java.awt.Dimension(100, 20));

        tprk1.setColumns(15);
        tprk1.setToolTipText("");
        tprk1.setMaximumSize(new java.awt.Dimension(100, 20));

        prk1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prk1.setText("praivte key");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tp1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(te1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pk1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prk1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tq1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(z1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tz1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(td1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tpk1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tprk1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tp1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tq1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tz1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(te1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(td1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pk1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpk1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prk1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tprk1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tprk2.setColumns(15);
        tprk2.setMaximumSize(new java.awt.Dimension(100, 20));

        prk2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prk2.setText("praivte key");

        pk2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pk2.setText("public key");

        tpk2.setColumns(15);
        tpk2.setMaximumSize(new java.awt.Dimension(100, 20));

        d2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        d2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d2.setText("d");

        e2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e2.setText("e");

        n2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n2.setText("n");

        z2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        z2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        z2.setText("z");

        q2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q2.setText("q");

        p2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2.setText("p");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tp2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(te2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tq2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(z2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tz2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(td2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tpk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tprk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tp2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tq2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tn2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tz2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(te2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(td2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pk2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpk2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prk2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tprk2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FillB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FillB.setText("Fill B");
        FillB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("plain text");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        EnAtoB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EnAtoB.setText("Encrypt  A send B");
        EnAtoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnAtoBActionPerformed(evt);
            }
        });

        EnBtoA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EnBtoA.setText("Encrypt  B send A");
        EnBtoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnBtoAActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("user A");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("user B");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("cipher text");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        DeAtoB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeAtoB.setText("Decrypt A send B");
        DeAtoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeAtoBActionPerformed(evt);
            }
        });

        DeBtoA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeBtoA.setText("Decrypt B send A");
        DeBtoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeBtoAActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("plain text");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("cipher text");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "from a to z", "from A to Z", "A to Z & a to z", "other input it" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("state for Language");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Language input");

        FillAuto.setText("Fill Automatclly");
        FillAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillAutoActionPerformed(evt);
            }
        });

        FillA.setText("Fill A");
        FillA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillAActionPerformed(evt);
            }
        });

        jButton11.setText("Resat");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FillAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lin, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FillA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FillB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnAtoB, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227)
                        .addComponent(EnBtoA, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeAtoB, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)
                        .addComponent(DeBtoA, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jScrollPane1)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jButton8)
                    .addComponent(jButton11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FillB, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(FillA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FillAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnAtoB)
                    .addComponent(EnBtoA)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeAtoB)
                        .addComponent(DeBtoA))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void FillBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillBActionPerformed
        // TODO add your handling code here
        if (chinB()) {
            fillB(tp2.getText(), tq2.getText(), te2.getText());
        } else {
            JOptionPane.showMessageDialog(rootPane, "No value enter or some value missed in user B data pleas enter them ");
        }
    }//GEN-LAST:event_FillBActionPerformed

    private void EnAtoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnAtoBActionPerformed
        // encrypt A send B :

        if (chinB()) {
            if (jComboBox1.getSelectedItem().toString().equals("from a to z")) {
                String[] sh = encryptAtoB(jTextField1.getText(), array);
                for (int x = 0; x < sh.length; x++) {
                    jTextArea1.setText(jTextArea1.getText() + " " + sh[x]);
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("from A to Z")) {
                String[] sh = encryptAtoB(jTextField1.getText(), array1);
                for (int x = 0; x < sh.length; x++) {
                    jTextArea1.setText(jTextArea1.getText() + " " + sh[x]);
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("A to Z & a to z")) {
                String[] sh = encryptAtoB(jTextField1.getText(), array2);
                for (int x = 0; x < sh.length; x++) {
                    jTextArea1.setText(jTextArea1.getText() + " " + sh[x]);
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("other input it")) {
                array3 = lin.getText().toCharArray();
                String[] sh = encryptAtoB(jTextField1.getText(), array3);
                for (int x = 0; x < sh.length; x++) {
                    jTextArea1.setText(jTextArea1.getText() + " " + sh[x]);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No value enter or some value missed in user B data pleas enter them ");
        }

    }//GEN-LAST:event_EnAtoBActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TO Clear Date in Plaintext & cipher output fileds 
        jTextField2.setText("");
        jTextArea2.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        //  TO Clear Date in Plaintext output & cipher fileds 

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void EnBtoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnBtoAActionPerformed
        // // encrypt B send A :
        if (chinA()) {
            if (jComboBox1.getSelectedItem().toString().equals("from a to z")) {
                String[] sh = encryptBtoA(jTextField1.getText(), array);
                for (int x = 0; x < sh.length; x++) {
                    jTextArea1.setText(jTextArea1.getText() + " " + sh[x]);
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("from A to Z")) {
                String[] sh = encryptBtoA(jTextField1.getText(), array1);
                for (int x = 0; x < sh.length; x++) {
                    jTextArea1.setText(jTextArea1.getText() + " " + sh[x]);
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("A to Z & a to z")) {
                String[] sh = encryptBtoA(jTextField1.getText(), array2);
                for (int x = 0; x < sh.length; x++) {
                    jTextArea1.setText(jTextArea1.getText() + " " + sh[x]);
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("other input it")) {
                array3 = lin.getText().toCharArray();
                String[] sh = encryptBtoA(jTextField1.getText(), array3);
                for (int x = 0; x < sh.length; x++) {
                    jTextArea1.setText(jTextArea1.getText() + " " + sh[x]);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No value enter or some value missed in user A data pleas enter them ");
        }
    }//GEN-LAST:event_EnBtoAActionPerformed

    private void DeAtoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeAtoBActionPerformed
        // TODO add your handling code here:
        if (chinB()) {
            if (jComboBox1.getSelectedItem().toString().equals("from a to z")) {
                char[] x = decryptAtoB(jTextField2.getText(), array);
                String x1 = String.copyValueOf(x);
                jTextArea2.setText(x1);
            } else if (jComboBox1.getSelectedItem().toString().equals("from A to Z")) {
                char[] x = decryptAtoB(jTextField2.getText(), array1);
                String x1 = String.copyValueOf(x);
                jTextArea2.setText(x1);
            } else if (jComboBox1.getSelectedItem().toString().equals("A to Z & a to z")) {
                char[] x = decryptAtoB(jTextField2.getText(), array2);
                String x1 = String.copyValueOf(x);
                jTextArea2.setText(x1);
            } else if (jComboBox1.getSelectedItem().toString().equals("other input it")) {
                array3 = lin.getText().toCharArray();
                char[] x = decryptAtoB(jTextField2.getText(), array3);
                String x1 = String.copyValueOf(x);
                jTextArea2.setText(x1);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No value enter or some value missed in user B data pleas enter them ");
        }
    }//GEN-LAST:event_DeAtoBActionPerformed

    private void DeBtoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeBtoAActionPerformed
        // TODO add your handling code here:
        if (chinA()) {
            if (jComboBox1.getSelectedItem().toString().equals("from a to z")) {
                char[] x = decryptBtoA(jTextField2.getText(), array);
                String x1 = String.copyValueOf(x);
                jTextArea2.setText(x1);
            } else if (jComboBox1.getSelectedItem().toString().equals("from A to Z")) {
                char[] x = decryptBtoA(jTextField2.getText(), array1);
                String x1 = String.copyValueOf(x);
                jTextArea2.setText(x1);
            } else if (jComboBox1.getSelectedItem().toString().equals("A to Z & a to z")) {
                char[] x = decryptBtoA(jTextField2.getText(), array2);
                String x1 = String.copyValueOf(x);
                jTextArea2.setText(x1);
            } else if (jComboBox1.getSelectedItem().toString().equals("other input it")) {
                array3 = lin.getText().toCharArray();
                char[] x = decryptBtoA(jTextField2.getText(), array3);
                String x1 = String.copyValueOf(x);
                jTextArea2.setText(x1);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No value enter or some value missed in user A data pleas enter them ");
        }
    }//GEN-LAST:event_DeBtoAActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Start st = new Start();
        st.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here: used to show language input when it needed
        if (jComboBox1.getSelectedItem().toString().equals("other input it")) {
            jLabel8.setVisible(true);
            lin.setVisible(true);
        } else {
            jLabel8.setVisible(false);
            lin.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void FillAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillAutoActionPerformed
        // TODO add your handling code here:
        fillA1();
        fillB1();
    }//GEN-LAST:event_FillAutoActionPerformed

    private void FillAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillAActionPerformed
        // TODO add your handling code here:
        if (chinA()) {
            fillA(tp1.getText(), tq1.getText(), te1.getText());
        } else {
            JOptionPane.showMessageDialog(rootPane, "No value enter or some value missed in user A data pleas enter them ");
        }
    }//GEN-LAST:event_FillAActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        RSA x = new RSA();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed
    //encrypt function when  A send to B
    public synchronized String[] encryptAtoB(String message, char[] arra) {
        char[] mss = message.toCharArray();
        String[] cip = new String[message.length()];
        String index = null;
        for (int y = 0; y < mss.length; y++) {
            for (int x = 0; x < arra.length; x++) {
                if (arra[x] == mss[y]) {
                    index = String.valueOf(x);
                    cip[y] = (new BigInteger(index)).modPow(ee, nn).toString();
                }
            }
//        cip[y]=(new BigInteger(index)).modPow(ee, nn).toString();
        }
        return cip;
    }

    //encrypt function when  B send to A
    public synchronized String[] encryptBtoA(String message, char[] arra) {
        char[] mss = message.toCharArray();
        String[] cip = new String[message.length()];
        String index = null;
        for (int y = 0; y < mss.length; y++) {
            for (int x = 0; x < arra.length; x++) {
                if (arra[x] == mss[y]) {
                    index = String.valueOf(x);
                    cip[y] = (new BigInteger(index)).modPow(e, n).toString();
                }
            }
//        cip[y]=(new BigInteger(index)).modPow(ee, nn).toString();
        }
        return cip;
    }

    // used to make all varable needed by user A
    public void fillA(String x, String x2, String x3) {
        tn1.setText("");
        tz1.setText("");
        te1.setText("");
        td1.setText("");
        tpk1.setText("");
        tprk1.setText("");
//        SecureRandom r = new SecureRandom();
//        p = new BigInteger(1024 / 2, 100, r);
//        q = new BigInteger(1024 / 2, 100, r);
        p = new BigInteger(x);
        q = new BigInteger(x2);
        if (chgcd(p, q) && chpremaria(p, q)) {
            n = p.multiply(q);
            z = (p.subtract(BigInteger.ONE)).multiply(q.subtract(BigInteger.ONE));
            e = new BigInteger(x3);
//        while (z.gcd(e).intValue() > 1) {
//            e = e.add(new BigInteger("2"));
//        }
            d = e.modInverse(z);
            if (d.equals(e)) {
                nd = d.add(z);
            } else {
                nd = d;
            }
            tn1.setText(n.toString());
            tz1.setText(z.toString());
            te1.setText(e.toString());
            td1.setText(nd.toString());
            tpk1.setText(e.toString() + "," + n.toString());
            tprk1.setText(d.toString() + "," + n.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "please enter right value for p & q for user A");
        }
    }

    // used to make all varable needed by user B automtaclly
    public void fillA1() {
        tn1.setText("");
        tz1.setText("");
        te1.setText("");
        td1.setText("");
        tpk1.setText("");
        tprk1.setText("");
        //restart:
        SecureRandom r = new SecureRandom();
        p = new BigInteger(1024 / 2, 100, r);
        q = new BigInteger(1024 / 2, 100, r);
        while(chpremaria(p, q)== false){
        p = new BigInteger(1024 / 2, 100, r);
        q = new BigInteger(1024 / 2, 100, r);
        }
        n = p.multiply(q);
        z = (p.subtract(BigInteger.ONE)).multiply(q.subtract(BigInteger.ONE));
        e = new BigInteger("3");
        while (z.gcd(e).intValue() > 1) {
            e = e.add(new BigInteger("2"));
        }
        d = e.modInverse(z);
        if (d.equals(e)) {
            nd = d.add(z);
        } else {
            nd = d;
        }
        tp1.setText(p.toString());
        tq1.setText(q.toString());
        tn1.setText(n.toString());
        tz1.setText(z.toString());
        te1.setText(e.toString());
        td1.setText(nd.toString());
        tpk1.setText(e.toString() + "," + n.toString());
        tprk1.setText(d.toString() + "," + n.toString());
        

    }

    // used to make all varable needed by user B
    public void fillB(String x, String x2, String x3) {
        tn2.setText("");
        tz2.setText("");
        te2.setText("");
        td2.setText("");
        tpk2.setText("");
        tprk2.setText("");
//        SecureRandom r = new SecureRandom();
//        pp = new BigInteger(1024 / 2, 100, r);
//        qq = new BigInteger(1024 / 2, 100, r);
        pp = new BigInteger(x);
        qq = new BigInteger(x2);
        if (chgcd(pp, qq) && chpremaria(pp, qq)) {
            nn = pp.multiply(qq);
            zz = (pp.subtract(BigInteger.ONE)).multiply(qq.subtract(BigInteger.ONE));
            ee = new BigInteger(x3);
//        while (z.gcd(e).intValue() > 1) {
//         e = e.add(new BigInteger("2"));
//        }
            dd = ee.modInverse(zz);
            if (dd.equals(ee)) {
                ndd = dd.add(zz);
            } else {
                ndd = dd;
            }
            tn2.setText(nn.toString());
            tz2.setText(zz.toString());
            te2.setText(ee.toString());
            td2.setText(ndd.toString());
            tpk2.setText(ee.toString() + "," + nn.toString());
            tprk2.setText(ndd.toString() + "," + nn.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "please enter right value for p & q for user B");
        }
    }

    // used to make all varable needed by user B automtaclly
    public void fillB1() {
        tn2.setText("");
        tz2.setText("");
        te2.setText("");
        td2.setText("");
        tpk2.setText("");
        tprk2.setText("");
        SecureRandom r = new SecureRandom();
        pp = new BigInteger(1024 / 2, 100, r);
        qq = new BigInteger(1024 / 2, 100, r);
          while(chpremaria(pp, qq)== false){
        pp = new BigInteger(1024 / 2, 100, r);
        qq = new BigInteger(1024 / 2, 100, r);
        }
        nn = pp.multiply(qq);
        zz = (pp.subtract(BigInteger.ONE)).multiply(qq.subtract(BigInteger.ONE));
        ee = new BigInteger("3");
        while (zz.gcd(ee).intValue() > 1) {
            ee = ee.add(new BigInteger("2"));
        }
        dd = ee.modInverse(zz);
        if (dd.equals(ee)) {
            ndd = dd.add(zz);
        } else {
            ndd = dd;
        }
        tp2.setText(pp.toString());
        tq2.setText(qq.toString());
        tn2.setText(nn.toString());
        tz2.setText(zz.toString());
        te2.setText(ee.toString());
        td2.setText(ndd.toString());
        tpk2.setText(ee.toString() + "," + nn.toString());
        tprk2.setText(ndd.toString() + "," + nn.toString());
    }

    //encrypt function when  A send to B
    public synchronized char[] decryptAtoB(String message, char[] arra) {
        String[] mss = message.split(" ");
        char[] plain = new char[100];
        for (int x = 0; x < mss.length; x++) {
            BigInteger index = (new BigInteger(mss[x])).modPow(ndd, nn);
            int index2 = index.intValue();
            plain[x] = arra[index2];
        }
        return plain;
    }

    //encrypt function when  B send to A
    public synchronized char[] decryptBtoA(String message, char[] arra) {
        String[] mss = message.split(" ");
        char[] plain = new char[100];
        for (int x = 0; x < mss.length; x++) {
            BigInteger index = new BigInteger(mss[x]).modPow(nd, n);
            int index2 = index.intValue();
            System.out.println(index2);
            plain[x] = arra[index2];
        }
        return plain;
    }
    
    // chack the needed input for user A if not founded to calculation
    public boolean chinA() {
        boolean test1 = (tp1.getText().equals("")) && (tq1.getText().equals("")) && (te1.getText().equals(""));
        boolean test1_1 = (tq1.getText().equals("")) && (te1.getText().equals(""));
        boolean test1_2 = (te1.getText().equals(""));
        if (test1 != true && test1_1 != true && test1_2 != true) {
            return true;
        } else {
            return false;
        }
    }
    
    // chack the needed input for user B if not founded to calculation
    public boolean chinB() {
        boolean test2 = (tp2.getText().equals("")) && (tq2.getText().equals("")) && (te2.getText().equals(""));
        boolean test2_1 = (tq2.getText().equals("")) && (te2.getText().equals(""));
        boolean test2_2 = (te2.getText().equals(""));
        if (test2 != true && test2_1 != true && test2_2 != true) {
            return true;
        } else {
            return false;
        }
    }
    
    // chack the gcd  input for two big intger
    public boolean chgcd(BigInteger x, BigInteger y) {
        if (x.gcd(y).intValue() == 1) {
            return true;
        } else {
            return false;
        }
    }
    
    // chack the premira  input for two big intger
    public boolean chpremaria(BigInteger x, BigInteger y) {
        if (x.isProbablePrime(2) && y.isProbablePrime(2)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeAtoB;
    private javax.swing.JButton DeBtoA;
    private javax.swing.JButton EnAtoB;
    private javax.swing.JButton EnBtoA;
    private javax.swing.JButton FillA;
    private javax.swing.JButton FillAuto;
    private javax.swing.JButton FillB;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField lin;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel pk1;
    private javax.swing.JLabel pk2;
    private javax.swing.JLabel prk1;
    private javax.swing.JLabel prk2;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JTextField td1;
    private javax.swing.JTextField td2;
    private javax.swing.JTextField te1;
    private javax.swing.JTextField te2;
    private javax.swing.JTextField tn1;
    private javax.swing.JTextField tn2;
    private javax.swing.JTextField tp1;
    private javax.swing.JTextField tp2;
    private javax.swing.JTextField tpk1;
    private javax.swing.JTextField tpk2;
    private javax.swing.JTextField tprk1;
    private javax.swing.JTextField tprk2;
    private javax.swing.JTextField tq1;
    private javax.swing.JTextField tq2;
    private javax.swing.JTextField tz1;
    private javax.swing.JTextField tz2;
    private javax.swing.JLabel z1;
    private javax.swing.JLabel z2;
    // End of variables declaration//GEN-END:variables
}
